export const typewriterWords = [
  {
    text: "Welcome",
  },
  {
    text: "to",
  },
  {
    text: "Cybotixx.",
    className: "dark:text-blue-500",
  },
];

export const textGenerateWords = `The ultimate online forum for computer science students! Whether you’re passionate about programming, algorithms, software development, or the latest advancements in technology, Cybotixx provides a vibrant community for you to explore, learn, and collaborate.`;

export const navLinks = [
  {
    label: "Home",
    link: "#"
  },
  {
    label: "Team",
    link: "#team"
  },
  {
    label: "Gallery",
    link: "#gallery"
  },
  {
    label: "About Us",
    link: "#about"
  }
];

export const galleryImages = [
  { link: "/assets/image (1).jpeg" },
  { link: "/assets/image (2).jpeg" },
  { link: "/assets/image (3).jpeg" },
  { link: "/assets/image (4).jpeg" },
  { link: "/assets/image (5).jpeg" },
  { link: "/assets/image (6).jpeg" },
  { link: "/assets/image (7).jpeg" },
  { link: "/assets/image (8).jpeg" },
  { link: "/assets/image (9).jpeg" },
  { link: "/assets/image (10).jpeg" },
  { link: "/assets/image (11).jpeg" },
  { link: "/assets/image (12).jpeg" },
  { link: "/assets/image (14).jpeg" },
  { link: "/assets/image (15).jpeg" },
  { link: "/assets/image (16).jpeg" },
  { link: "/assets/image (17).jpeg" },
  { link: "/assets/image (18).jpeg" },
  { link: "/assets/image (19).jpeg" },
  { link: "/assets/image (20).jpeg" },
  { link: "/assets/image (21).jpeg" },
  { link: "/assets/image (1).jpeg" },
  { link: "/assets/image (2).jpeg" },
  { link: "/assets/image (3).jpeg" },
  { link: "/assets/image (4).jpeg" },
  { link: "/assets/image (5).jpeg" },
  { link: "/assets/image (6).jpeg" },
  { link: "/assets/image (7).jpeg" },
  { link: "/assets/image (8).jpeg" },
  { link: "/assets/image (9).jpeg" },
  { link: "/assets/image (10).jpeg" },
  { link: "/assets/image (11).jpeg" },
  { link: "/assets/image (12).jpeg" },
  { link: "/assets/image (14).jpeg" },
  { link: "/assets/image (15).jpeg" },
  { link: "/assets/image (16).jpeg" },
  { link: "/assets/image (17).jpeg" },
  { link: "/assets/image (18).jpeg" },
  { link: "/assets/image (19).jpeg" },
  { link: "/assets/image (20).jpeg" },
  { link: "/assets/image (21).jpeg" },
  { link: "/assets/image (1).jpeg" },
  { link: "/assets/image (2).jpeg" },
  { link: "/assets/image (3).jpeg" },
  { link: "/assets/image (4).jpeg" },
  { link: "/assets/image (5).jpeg" },
  { link: "/assets/image (6).jpeg" },
  { link: "/assets/image (7).jpeg" },
  { link: "/assets/image (8).jpeg" },
  { link: "/assets/image (9).jpeg" },
  { link: "/assets/image (10).jpeg" },
  { link: "/assets/image (11).jpeg" },
  { link: "/assets/image (12).jpeg" },
  { link: "/assets/image (14).jpeg" },
  { link: "/assets/image (15).jpeg" },
  { link: "/assets/image (16).jpeg" },
  { link: "/assets/image (17).jpeg" },
  { link: "/assets/image (18).jpeg" },
  { link: "/assets/image (19).jpeg" },
  { link: "/assets/image (20).jpeg" },
  { link: "/assets/image (21).jpeg" },
  { link: "/assets/image (1).jpeg" },
  { link: "/assets/image (2).jpeg" },
  { link: "/assets/image (3).jpeg" },
  { link: "/assets/image (4).jpeg" },
  { link: "/assets/image (5).jpeg" },
  { link: "/assets/image (6).jpeg" },
  { link: "/assets/image (7).jpeg" },
  { link: "/assets/image (8).jpeg" },
  { link: "/assets/image (9).jpeg" },
  { link: "/assets/image (10).jpeg" },
  { link: "/assets/image (11).jpeg" },
  { link: "/assets/image (12).jpeg" },
  { link: "/assets/image (14).jpeg" },
  { link: "/assets/image (15).jpeg" },
  { link: "/assets/image (16).jpeg" },
  { link: "/assets/image (17).jpeg" },
  { link: "/assets/image (18).jpeg" },
  { link: "/assets/image (19).jpeg" },
  { link: "/assets/image (20).jpeg" },
  { link: "/assets/image (21).jpeg" },
  { link: "/assets/image (1).jpeg" },
  { link: "/assets/image (2).jpeg" },
  { link: "/assets/image (3).jpeg" },
  { link: "/assets/image (4).jpeg" },
  { link: "/assets/image (5).jpeg" },
  { link: "/assets/image (6).jpeg" },
  { link: "/assets/image (7).jpeg" },
  { link: "/assets/image (8).jpeg" },
  { link: "/assets/image (9).jpeg" },
  { link: "/assets/image (10).jpeg" },
  { link: "/assets/image (11).jpeg" },
  { link: "/assets/image (12).jpeg" },
  { link: "/assets/image (14).jpeg" },
  { link: "/assets/image (15).jpeg" },
  { link: "/assets/image (16).jpeg" },
  { link: "/assets/image (17).jpeg" },
  { link: "/assets/image (18).jpeg" },
  { link: "/assets/image (19).jpeg" },
  { link: "/assets/image (20).jpeg" },
  { link: "/assets/image (21).jpeg" },
  { link: "/assets/image (1).jpeg" },
  { link: "/assets/image (2).jpeg" },
  { link: "/assets/image (3).jpeg" },
  { link: "/assets/image (4).jpeg" },
  { link: "/assets/image (5).jpeg" },
  { link: "/assets/image (6).jpeg" },
  { link: "/assets/image (7).jpeg" },
  { link: "/assets/image (8).jpeg" },
  { link: "/assets/image (9).jpeg" },
  { link: "/assets/image (10).jpeg" },
  { link: "/assets/image (11).jpeg" },
  { link: "/assets/image (12).jpeg" },
  { link: "/assets/image (14).jpeg" },
  { link: "/assets/image (15).jpeg" },
  { link: "/assets/image (16).jpeg" },
  { link: "/assets/image (17).jpeg" },
  { link: "/assets/image (18).jpeg" },
  { link: "/assets/image (19).jpeg" },
  { link: "/assets/image (20).jpeg" },
  { link: "/assets/image (21).jpeg" },
  { link: "/assets/image (1).jpeg" },
  { link: "/assets/image (2).jpeg" },
  { link: "/assets/image (3).jpeg" },
  { link: "/assets/image (4).jpeg" },
  { link: "/assets/image (5).jpeg" },
  { link: "/assets/image (6).jpeg" },
  { link: "/assets/image (7).jpeg" },
  { link: "/assets/image (8).jpeg" },
  { link: "/assets/image (9).jpeg" },
  { link: "/assets/image (10).jpeg" },
  { link: "/assets/image (11).jpeg" },
  { link: "/assets/image (12).jpeg" },
  { link: "/assets/image (14).jpeg" },
  { link: "/assets/image (15).jpeg" },
  { link: "/assets/image (16).jpeg" },
  { link: "/assets/image (17).jpeg" },
  { link: "/assets/image (18).jpeg" },
  { link: "/assets/image (19).jpeg" },
  { link: "/assets/image (20).jpeg" },
  { link: "/assets/image (21).jpeg" },
  { link: "/assets/image (1).jpeg" },
  { link: "/assets/image (2).jpeg" },
  { link: "/assets/image (3).jpeg" },
  { link: "/assets/image (4).jpeg" },
  { link: "/assets/image (5).jpeg" },
  { link: "/assets/image (6).jpeg" },
  { link: "/assets/image (7).jpeg" },
  { link: "/assets/image (8).jpeg" },
  { link: "/assets/image (9).jpeg" },
  { link: "/assets/image (10).jpeg" },
  { link: "/assets/image (11).jpeg" },
  { link: "/assets/image (12).jpeg" },
  { link: "/assets/image (14).jpeg" },
  { link: "/assets/image (15).jpeg" },
  { link: "/assets/image (16).jpeg" },
  { link: "/assets/image (17).jpeg" },
  { link: "/assets/image (18).jpeg" },
  { link: "/assets/image (19).jpeg" },
  { link: "/assets/image (20).jpeg" },
  { link: "/assets/image (21).jpeg" },
  { link: "/assets/image (1).jpeg" },
  { link: "/assets/image (2).jpeg" },
  { link: "/assets/image (3).jpeg" },
  { link: "/assets/image (4).jpeg" },
  { link: "/assets/image (5).jpeg" },
  { link: "/assets/image (6).jpeg" },
  { link: "/assets/image (7).jpeg" },
  { link: "/assets/image (8).jpeg" },
  { link: "/assets/image (9).jpeg" },
  { link: "/assets/image (10).jpeg" },
  { link: "/assets/image (11).jpeg" },
  { link: "/assets/image (12).jpeg" },
  { link: "/assets/image (14).jpeg" },
  { link: "/assets/image (15).jpeg" },
  { link: "/assets/image (16).jpeg" },
  { link: "/assets/image (17).jpeg" },
  { link: "/assets/image (18).jpeg" },
  { link: "/assets/image (19).jpeg" },
  { link: "/assets/image (20).jpeg" },
  { link: "/assets/image (21).jpeg" },
];


export const teamMembers = [
  {
    name: "Praveen Raj R",
    position: "President",
  },
  {
    name: "Junaid Khan",
    position: "Vice President",
  },
  {
    name: "Manoj J",
    position: "Head",
  },
  {
    name: "Mohammed Falah",
    position: "Head",
  },
  {
    name: "Sushanth Shetty",
    position: "Core Member",
  },
  {
    name: "Swaroop C N",
    position: "Core Member",
  },
  {
    name: "Likitha J",
    position: "Core Member"
  },
  {
    name: "Nethra K S",
    position: "Core Member"
  },
  {
    name: "Yameen Afroz",
    position: "Core Member"
  },
];
