import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Modals from "@/components/modals";
import { Toaster } from "sonner";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  weight: ["500", "400", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Cybotixx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <head>
        <link rel="icon" href="/favicon.png" type="image/png" />
      </head>
      <body className={`${inter.className} antialiased min-h-screen relative`}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          {children}
          <Modals />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
