import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import JotaiProvider from "@/components/jotai-provider";
import { BackgroundBeams } from "@/components/ui/background-beams";
import Modals from "@/components/modals";
import { Toaster } from "sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Cybotixx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <head>
        <link rel="icon" href="/favicon.png" type="image/png" />
      </head>
      <JotaiProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-screen-2xl min-h-screen relative`}
        >
          <ThemeProvider attribute="class" defaultTheme="dark">
            <Navbar />
            {children}
            <Modals />
            <Toaster />
            <BackgroundBeams className="-z-40 fixed top-0 left-0 opacity-80" />
          </ThemeProvider>
        </body>
      </JotaiProvider>
    </html>
  );
}
